# Generated by Django 4.2.2 on 2023-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='рейтинг товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_text',
            field=models.TextField(verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=200, verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата публикации товара'),
        ),
    ]
